services:
  postgres:
    image: postgres:17
    container_name: trainingnutrition_db
    environment:
      POSTGRES_USER: tnuser
      POSTGRES_PASSWORD: tnpassword
      POSTGRES_DB: trainingnutrition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: