// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainingNutrition.Infrastructure;

#nullable disable

namespace TrainingNutrition.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainingNutrition.Domain.Dishes.Dish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Ingredients.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Ingredients.IngredientEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientEntries");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Meals.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Tracking.DailyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Dishes.Dish", b =>
                {
                    b.HasOne("TrainingNutrition.Domain.Meals.Meal", null)
                        .WithMany("Dishes")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Ingredients.Ingredient", b =>
                {
                    b.OwnsOne("TrainingNutrition.Domain.Common.Macronutrients", "MacrosPer100g", b1 =>
                        {
                            b1.Property<Guid>("IngredientId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Carbs")
                                .HasColumnType("numeric")
                                .HasColumnName("Carbs");

                            b1.Property<decimal>("Fat")
                                .HasColumnType("numeric")
                                .HasColumnName("Fat");

                            b1.Property<decimal>("Fiber")
                                .HasColumnType("numeric")
                                .HasColumnName("Fiber");

                            b1.Property<decimal>("Protein")
                                .HasColumnType("numeric")
                                .HasColumnName("Protein");

                            b1.Property<decimal>("Salt")
                                .HasColumnType("numeric")
                                .HasColumnName("Salt");

                            b1.HasKey("IngredientId");

                            b1.ToTable("Ingredients");

                            b1.WithOwner()
                                .HasForeignKey("IngredientId");
                        });

                    b.Navigation("MacrosPer100g")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Ingredients.IngredientEntry", b =>
                {
                    b.HasOne("TrainingNutrition.Domain.Dishes.Dish", null)
                        .WithMany("Entries")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrainingNutrition.Domain.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TrainingNutrition.Domain.Common.Grams", "Grams", b1 =>
                        {
                            b1.Property<Guid>("IngredientEntryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Grams");

                            b1.HasKey("IngredientEntryId");

                            b1.ToTable("IngredientEntries");

                            b1.WithOwner()
                                .HasForeignKey("IngredientEntryId");
                        });

                    b.Navigation("Grams")
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Meals.Meal", b =>
                {
                    b.HasOne("TrainingNutrition.Domain.Tracking.DailyLog", null)
                        .WithMany("Meals")
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Users.User", b =>
                {
                    b.OwnsOne("TrainingNutrition.Domain.Common.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Dishes.Dish", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Meals.Meal", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("TrainingNutrition.Domain.Tracking.DailyLog", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
